// Statements & readouts — screen (b). Lists the firm's documents with download
// links. Per-period document records land with the pipeline gate; for now this
// lists the rendered statement + readout (labeled demo where synthetic).
import Link from "next/link";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const metadata = { title: "Statements & readouts — Intake QA" };

const DOCS = [
  {
    label: "Intake Leak Report — June 2026",
    period: "June 2026",
    issued: "Jul 5, 2026",
    status: "Issued (demo)",
    href: "/api/documents/leak-report",
  },
  {
    label: "Missed-Revenue Statement — June 2026",
    period: "June 2026",
    issued: "Jul 5, 2026",
    status: "Issued (demo)",
    href: "/api/documents/statement",
  },
  {
    label: "Leak Audit — Jun 1–30, 2026",
    period: "Jun 1–30, 2026",
    issued: "Jul 5, 2026",
    status: "Issued (demo)",
    href: "/api/documents/readout",
  },
];

export default function DocumentsPage() {
  return (
    <div>
      <div className="mb-6">
        <p className="eyebrow">The desk</p>
        <h1 className="mt-1 font-display text-2xl font-semibold text-ink">Statements &amp; readouts</h1>
        <p className="mt-1 text-sm text-ink-muted">
          Every readout the desk has issued for your firm. Each is a written PDF you own.
        </p>
      </div>

      <div className="overflow-x-auto rounded-card border border-hairline">
        <table className="w-full min-w-[640px] text-sm">
          <thead>
            <tr className="border-b border-hairline bg-canvas text-xs uppercase tracking-wide text-ink-muted">
              <th className="px-4 py-2.5 text-left">Document</th>
              <th className="px-4 py-2.5 text-left">Period</th>
              <th className="px-4 py-2.5 text-left">Issued</th>
              <th className="px-4 py-2.5 text-left">Status</th>
              <th className="px-4 py-2.5 text-right">Download</th>
            </tr>
          </thead>
          <tbody>
            {DOCS.map((d) => (
              <tr key={d.href} className="border-b border-hairline last:border-0">
                <td className="px-4 py-3 font-medium text-ink">{d.label}</td>
                <td className="px-4 py-3 text-ink-muted">{d.period}</td>
                <td className="px-4 py-3 text-ink-muted">{d.issued}</td>
                <td className="px-4 py-3 text-ink-muted">{d.status}</td>
                <td className="px-4 py-3 text-right">
                  <Link
                    href={d.href}
                    className="rounded-pill bg-accent px-4 py-1.5 text-xs font-semibold text-white hover:bg-accent-hover"
                  >
                    Download PDF
                  </Link>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="mt-4 text-xs text-faint">
        Documents labeled &ldquo;demo&rdquo; render from synthetic data. Per-firm, per-period documents
        are generated by the pipeline once your calls are processed.
      </p>
    </div>
  );
}
