// Onboarding: firm-config builder (pure).
//
// Turns the wizard's answers into (1) a normalized firm record for the DB and
// (2) a firm-config markdown in the SAME shape as config/demo-firm.md, which is
// itself a copy of scoring/firm-config-template.md. The scoring template in
// scoring/ is a CALIBRATED artifact and is never edited; we only ever COPY its
// field layout here so a real firm's config drops into the scorer unchanged.
//
// No I/O, no network — the API route persists the record and (best-effort)
// writes the markdown. Tested in tests/onboard.test.mjs.

// The common California PI case types offered in the wizard, with conservative
// default fee ESTIMATES (whole dollars). A firm overrides any of these; the
// values are labeled as estimates until the firm confirms its real numbers.
export const CASE_TYPE_CATALOG = [
  { key: "mva_standard", label: "Auto accident (standard)", defaultFee: 12000 },
  { key: "mva_commercial", label: "Auto accident (commercial vehicle)", defaultFee: 45000 },
  { key: "motorcycle", label: "Motorcycle accident", defaultFee: 25000 },
  { key: "premises", label: "Premises / slip-and-fall", defaultFee: 18000 },
  { key: "dog_bite", label: "Dog bite", defaultFee: 15000 },
  { key: "pedestrian", label: "Pedestrian / bicycle", defaultFee: 22000 },
  { key: "wrongful_death", label: "Wrongful death", defaultFee: 150000 },
];

const CATALOG_BY_KEY = new Map(CASE_TYPE_CATALOG.map((c) => [c.key, c]));

function cleanStr(v) {
  return typeof v === "string" ? v.trim() : "";
}

// Normalize raw wizard input into a validated firm record. Throws on the few
// things that must be present (a name, at least one accepted case type).
// `accepted` is [{ key, fee }]; unknown keys are dropped, fees coerced to ints.
export function normalizeFirmInput(raw = {}) {
  const name = cleanStr(raw.name);
  if (!name) throw new Error("Firm name is required.");

  const timezone = cleanStr(raw.timezone) || "America/Los_Angeles";

  const accepted = [];
  for (const item of Array.isArray(raw.accepted) ? raw.accepted : []) {
    const key = cleanStr(item?.key);
    const cat = CATALOG_BY_KEY.get(key);
    if (!cat) continue;
    const feeNum = Number(item?.fee);
    const fee = Number.isFinite(feeNum) && feeNum > 0 ? Math.round(feeNum) : cat.defaultFee;
    accepted.push({ key, label: cat.label, fee });
  }
  if (accepted.length === 0) throw new Error("Select at least one case type your firm accepts.");

  // avg_case_fee (feeds reconciliation math) = mean of accepted fees, whole $.
  const avgCaseFee = Math.round(accepted.reduce((s, a) => s + a.fee, 0) / accepted.length);

  const subRaw = Number(raw.subscriptionPrice);
  const subscriptionPrice =
    Number.isFinite(subRaw) && subRaw > 0 ? Math.round(subRaw) : null;

  const declined = CASE_TYPE_CATALOG
    .filter((c) => !accepted.some((a) => a.key === c.key))
    .map((c) => c.key);

  return { name, timezone, accepted, declined, avgCaseFee, subscriptionPrice };
}

// Build the firm-config markdown (same field layout as config/demo-firm.md).
// Fee values are labeled estimates until the firm confirms them.
export function buildFirmConfigMarkdown(firm) {
  const acceptedKeys = firm.accepted.map((a) => a.key).join(", ");
  const declinedKeys = firm.declined.join(", ") || "none";
  const feeLine = firm.accepted
    .map((a) => `${a.key} $${a.fee.toLocaleString("en-US")}`)
    .join("; ");
  return [
    `FIRM CONFIG (${firm.name}) — generated by the Intake QA onboarding wizard.`,
    `Fee values are ESTIMATES until confirmed by the firm. Copied field layout from`,
    `scoring/firm-config-template.md (the calibrated template is never edited).`,
    ``,
    `firm_name: ${firm.name}`,
    `state: CA`,
    `firm_size: small_2_10`,
    `case_types_accepted: ${acceptedKeys}`,
    `case_types_declined: ${declinedKeys}`,
    `minimum_case_criteria: default`,
    `auto_escalate_indicators: default`,
    `average_fee_by_case_type: ${feeLine}`,
    `fee_values_estimated: true`,
    `esign_on_call_enabled: true`,
    `esign_tool: Dropbox Sign`,
    `same_call_sign_policy: encouraged`,
    `languages_supported: en`,
    `rep_roster: Intake team`,
    `referral_out_protocol: default`,
    `recorded_statement_policy: default`,
    `sol_urgency_thresholds: default (CA)`,
    `timezone: ${firm.timezone}`,
    `special_instructions: none`,
    ``,
  ].join("\n");
}
