// The Unscored Conversation — final, legally-reviewed essay body, stored VERBATIM.
//
// This is the single source of truth for the rendered letter. Punctuation is the
// author's own final revision: curly quotes (“ ” ‘ ’), em dashes eliminated except
// where critically necessary (the one inside the quoted ISO standard title), and en
// dashes kept only in numeric ranges. Do NOT run any typographic/smart-quote
// transform over this text and do NOT reformat it — it is already exactly as the
// author (Ali Ansari) wants it. The letter route renders it with a tiny
// deterministic markdown subset (paragraphs, "## " headings, and *italic* spans
// only) — no remark, no smartypants — so nothing here is ever re-punctuated.
//
// Body runs from the opening paragraph through the final line; the signature
// (“— Ali Ansari, Analyst of Record, Intake QA”) is rendered in the attestation.

export const DECK =
  "Personal injury firms measure everything about intake except the four minutes that decide it, and the other side of your cases has been scoring that conversation for thirty years.";

export const ESSAY_BODY = `My name is Ali Ansari. Before I tell you anything about your firm, I am going to tell you something about myself, and I am going to sign my name to all of it. I am twenty-three. I studied philosophy. But the part of my life that matters to you is smaller and less flattering: for a stretch of my early twenties I sat at the intake desk of a plaintiff-side personal injury firm in the Bay Area, and I answered the phone when people called on the worst day of their lives. I took the calls in English and in Spanish. I learned, fast, that the difference between a signed case and a lost one was usually not the facts of the injury. It was what happened in the first four minutes of a phone call that no one ever listened to again.

I remember a woman who called on her lunch break (I could hear a break room behind her) about a fall at work, and I ran my screen so briskly, so efficiently, that she apologized to me for wasting my time and hung up. She had a case, and I had made her feel like a nuisance in the ninety seconds it took to lose her. I never heard from her again. That call is why this company exists.

I am going to make one claim in this letter and spend the rest of it earning it: your firm measures everything about intake except the one thing that decides it. You measure cost per lead, speed to contact, answer rate, source, and sign rate by staffer. You do not measure the conversation. No one in your office has ever pulled the recording of the call where a frightened, hurting, often Spanish-speaking human being decided whether to trust you, and scored how it was handled, and no one ever will, unless someone outside your office does it. I want to be that person.

You are reading this at the end of a long day, and your inbox tonight is full of vendor emails that a machine wrote: fluent, confident, interchangeable. This is not one of them. A person wrote this, a person is accountable for every number in it, and that is now the rarest thing a document can offer you. Because I am asking you to trust a number I produce, I will do the thing almost no one selling you anything will do: I bind myself to a published error rate. Intake QA maintains a public Calibration & Honesty page that states the method, the two ways the scoring fails, and the numbers I will not print until the test corpus behind them is documented. The false-alarm rate goes on that page, in public, as the calls come in, and nothing goes up before it can be checked. I will come back to why that page exists. For now, it is the whole argument in miniature. In a world where anyone can generate fluent, confident, sourceless language on demand, words are cheap and getting cheaper. The only expensive thing left is a person willing to put something at risk behind what they say. This letter is signed for that reason. The number I want to hand you is signed for that reason too.

Let me start by conceding everything I can. Your CRM is good. If you run Litify or Lead Docket, you have dashboards that most firms would have killed for a decade ago. You can see conversion by referral source, speed-to-contact down to the minute, and which intake specialist signs at what rate. Anyone who tells you that you are “flying blind” on intake is selling you fear, and you should distrust them. You are not blind to your outcomes.

Concede more. In 2025 and 2026 a whole wave of AI intake tools has arrived that goes further: conversational qualifiers that talk to a caller, score the lead, and drop a transcript into your system; voice bots that pre-screen for accident type, liability, and the statute of limitations before a human ever picks up. Some of them are good. If you have bought one, you did not waste your money. But notice what every one of them scores: the lead. The case. Whether the matter is worth taking. Not one of them turns around and audits how your own people handled the human being on the other end of the line (the empathy, the sense of control, the trust) against a published behavioral standard, and then tells you, in numbers it will stand behind, how often that handling cost you a case. That is a different instrument, and it is the one no one has built.

Your people work hard. The intake staff I have met are not lazy or careless. They are underpaid, over-volumed, and asked to make five-, six-, and seven-figure judgments about human beings in the length of a phone call, with no rubric and no feedback loop. A single signed file can be worth six or seven figures in fees. The call that gates it is, in raw economic terms, the most expensive conversation in your business, and it is the only one you have never listened back to. That is not a character problem. It is a design problem.

That brings me to the single uncovered fact, and I have conceded enough that it should land without flinching. Your CRM scores the outcome. It does not score the conversation. It records that a call happened, how long it lasted, and whether it converted. It cannot tell you why it converted, or, far more expensively, why it didn’t. The most consequential four minutes in your entire business are the one part of it you have never instrumented. Everything below is about that gap: why it exists, why it persists, why the other side closed it thirty years ago, and what it costs you every month that you leave it open.

## I. THE FOURTH TRANSFORMATION

There is a paper every law-and-society scholar knows and almost no practicing lawyer has read. In 1980, William Felstiner, Richard Abel, and Austin Sarat published “The Emergence and Transformation of Disputes: Naming, Blaming, Claiming…” in the *Law & Society Review* (15 Law & Soc’y Rev. 631). It is one of the most cited articles in the entire field, and its idea is simple enough to carry in your pocket.

Every legal claim, they argued, is the survivor of three transformations. First, naming: the injured person has to recognize that what happened to them is an injury at all, that the pain in their neck is a harm and not just a bad week. Then, blaming: they have to decide that someone else is responsible. Then, claiming: they have to voice that grievance to the party they blame and demand something. Most injuries die at the first or second step. They never become anything.

The evidence on this is about as settled as the sociology of law gets. David Engel’s *The Myth of the Litigious Society* (University of Chicago Press, 2016) collects it: more than 90 percent of injured people “lump” their losses. They absorb the harm and make no claim at all, even when the law is plainly on their side. By Engel’s account, about 4 percent hire a lawyer, and only 2 to 3 percent ever file suit. The story America tells about itself, a nation of eager plaintiffs, is simply false. We are a nation of lumpers.

Now the part the 1980 paper never named. There is a fourth transformation. It happens after claiming, and it is the one your firm lives or dies on. It is the moment a grievance-holder becomes a represented claimant: the handoff from self-help to institutional advocacy. It is the intake call. It is the instant a person who has decided, alone and afraid, that they were wronged, picks up a phone to place their grievance in the hands of a stranger with a bar card. The relationship that begins there has been studied for decades under the heading of lawyer and client. What has never been done is to treat the handoff itself as its own transformation: to name it, and to hold it to a scored standard. Felstiner, Abel, and Sarat gave us naming, blaming, and claiming. The intake call is the fourth verb. Call it entrusting.

Your real competitor is not the firm on the next billboard. Your real competitor is silence: the gravitational pull back into that 90 percent who do nothing. A person mid-way through the fourth transformation is not a committed client. They are a wavering human being who has taken one brave step and is looking for a reason to retreat. A fumbled call (a cold tone, a rushed screen, a hold that runs too long, a question that makes them feel like a suspect) does not send them to your competitor. It sends them home, back into lumping, to become one more uncounted person who decided the whole thing wasn’t worth it.

And the door is narrowing. In a 2025 essay honoring Deborah Hensler, RAND researchers James Anderson, Maya Buenaventura, Amy Mahler, and Nicholas Pace (*Empirical Tort Law (and Theory)*, 17 J. Tort L. 97) updated Hensler’s classic 1980s claiming study and found that injured people who reach out to attorneys today are “much more likely to be turned away by the attorneys they contacted when compared to the ICJ-Hensler respondents of 1988–89 (53% turned away vs. 22% turned away).” More than half of the people who complete the fourth transformation (who summon the courage to call) are now shown the door. Some of that screening is sound underwriting. But without measuring the conversation, you cannot tell the difference between a case you rejected and a case you lost. Both show up in your CRM as the same thing: a call that didn’t convert.

## II. IT HAS ALREADY BEEN DONE

Whenever I describe scored, audited, protocol-driven evaluation of high-stakes phone calls to a managing partner, I get the same reaction: interesting in theory, impossible in practice. You can’t standardize something as human as a distress call. Except it has already been done, at massive scale, for nearly half a century, in a domain with stakes considerably higher than yours.

In 1979, a physician named Jeff Clawson began building what became the Medical Priority Dispatch System, a structured protocol for the person who answers when you call 911. Before Clawson, the call-taker was improvising: whoever picked up, using whatever judgment they had. After Clawson, the call-taker worked a script with defined questions, defined codes, and (this is the crucial part) mandatory, random, retrospective audit of recorded calls against the protocol. The International Academies of Emergency Dispatch built a Board of Accreditation around it in 1992, with a defined compliance standard and case review scaled to call volume: higher-volume centers review more calls.

Why the audit? Because the field learned, empirically, that the protocol alone does not hold. Clawson and colleagues demonstrated in *Annals of Emergency Medicine* in 1998 (32:578–584) that giving dispatchers regular, objective feedback on their recorded performance dramatically increased how rigorously they followed the protocol. Their own conclusion is blunt: “Providing emergency medical dispatchers with regular and objective feedback regarding their performance dramatically improves how rigorously they follow a systematized dispatch protocol.” Without ongoing review, compliance decays. The number written in the protocol is not the number you get on the floor. You get the number you audit.

And when you do audit, at scale, the standard holds. The London Ambulance Service, which handles more than two million 999 calls a year and is among the busiest emergency operations in the world, runs just this kind of accredited, protocol-driven, feedback-driven system, held to an accreditation standard requiring better than 90 percent protocol compliance, with published audits of such accredited centres reporting mean compliance in the high-90-percent range. That is what a scored, audited crisis-call operation looks like at scale, because someone is listening to the tape.

One more thing, and it should sting. There is a formal international standard for the discipline you practice every day and have never measured. ISO 18295-1:2017, “Customer contact centres — Part 1,” requires that a contact centre take action to measure and monitor the customer experience, and it lists the methods by which to do so, including, in its own words, “the CCC’s quality evaluation” and “speech analytics.” There is an international standard for answering the phone. Your intake desk would not pass its audit.

Put the two calls side by side. When a person calls 911 while they are bleeding, a trained specialist works a scored protocol under mandatory random audit, and if they deviate, someone listens to the recording and corrects them. When that same person calls a law firm while they are bleeding (financially, physically, at the worst moment of their life) they get whoever happened to pick up, working from memory and mood, and no one will ever listen to the recording. Not once. The tape, if it exists at all, exists so it can be produced in discovery or used to defend against a bar complaint. It is never used to get better.

## III. THE ASYMMETRY

What I find hardest to forgive is also the fact I most want you to remember. The other side of your case already scores the call. You’ve never even listened to it.

The defense-side insurance industry figured out, decades ago, that the telephone conversation with a claimant is a measurable, optimizable, revenue-controlling event, and they built an apparatus to measure it, while the plaintiff’s bar kept eyeballing intake by gut.

Start with the settlement machine. In 1992, Allstate hired McKinsey & Company to redesign its claims operation, the “Claims Core Process Redesign,” documented in David Berardinelli’s *From Good Hands to Boxing Gloves* (Trial Guides, 2008), the book built from some 12,500 McKinsey slides pried loose in litigation. There is a single word in those slides worth the price of this whole letter. McKinsey’s term for paying a claimant more than the minimum (for money escaping the company toward the injured person) was *leakage*. Sit with that word, and then sit with the one I use. On the defense side, “leakage” is your client’s fair recovery escaping to your client. On your side, the leak runs the other way: it is the case itself, escaping back into silence, at intake. They built a thirty-year science to stop their leak. You have never measured yours. By Berardinelli’s accounting, Allstate’s average annual pre-tax operating income was about $82 million in the decade before the redesign; in the years after, it averaged around $2.4 billion. That is what happens when one side treats the claims interaction as an engineering problem and the other treats it as folklore.

Then the valuation engine. Colossus, the bodily-injury settlement software originally from Computer Sciences Corporation and now owned by DXC Technology, reduces the worth of a human injury to a point-scored range. According to CSC’s own marketing, it has been used by “thirteen of the top twenty” U.S. property-and-casualty insurers; a former Farmers Insurance employee who left to consult for plaintiffs’ lawyers has estimated that insurers save 15 to 30 percent on injury payouts by using it. When your client’s pain is on the other end of a negotiation, it is being priced by an actuarial instrument, not a person’s sympathy.

And now the frontier: voice analytics at First Notice of Loss. Insurers are deploying voice-risk-assessment tools, the vendor Clearspeed among them, that, as summarized in trade-press coverage of remarks by Allianz UK’s chief claims officer, Matt Cox, are “embedded directly into the claims process, asking customers yes/no questions and generating a real-time risk signal to guide whether claims should be paid or investigated.” Allianz UK’s announcement of September 23, 2025 reported that it “uncovered more than 15,800 instances of insurance fraud across personal, commercial and specialty lines worth a total of £92.6m in the first half of 2025 – up 34% (£68.9m) on the same period in 2024,” naming “voice analytic partner Clearspeed” as part of how it did it. As the insurer reports it, the industry that pays your clients is now scoring the conversation (the paralinguistics, the hesitations, the words) at the moment of the claim. They are already living in the world I am describing to you. They are just standing on the opposite side of it.

So the asymmetry is total. The people who profit from underpaying your clients have spent thirty years and untold millions learning to measure the claim conversation. The people who represent those clients have spent the same thirty years not listening to their own tapes. You are bringing gut instinct to a fight against actuaries.

## IV. THE FIVE BLINDNESSES

If measuring the intake conversation is so obviously valuable, if the other side proved it, if there’s an ISO standard, if 911 solved it in 1979, then why does the leak persist? The answer is not stupidity but a stack of specific, well-documented blindnesses, and naming them is the only way to fix the problem instead of moralizing about it.

First, a credibility blindness. The philosopher Miranda Fricker gave us the term *testimonial injustice* (*Epistemic Injustice*, Oxford University Press, 2007): a hearer gives “a deflated level of credibility to a speaker’s word” because of “identity prejudice,” the speaker’s accent, disorganization, distress, or social type. Picture your intake desk. The caller who is hardest to understand (crying, or whose English is halting, or who tells the story out of order because trauma scrambles narrative) receives an unearned credibility deficit at the precise instant they are trying to complete the fourth transformation. The people the tort system exists to protect are the ones most likely to be waved off in the first four minutes, and it happens below the level of anyone’s conscious decision. You cannot correct a bias you have never recorded.

Second, a policy blindness. Michael Lipsky’s *Street-Level Bureaucracy* (1980) established a truth every executive resists: the frontline worker with discretion is the organization’s real policy, whatever the official policy says. The intake specialist earning somewhere between $20 and $28 an hour in the California market is not merely executing your case-selection strategy. That person *is* your case-selection strategy (the actual, operative one), and it is invisible to you, the owner, because it lives in a thousand unrecorded conversational judgments rather than in any document you have ever signed.

Third, a method blindness. In 1954, Paul Meehl published *Clinical Versus Statistical Prediction* and started an argument that is now over. The 2000 meta-analysis by Grove and colleagues (*Psychological Assessment*, 12:19–30) found that “mechanical-prediction techniques were about 10% more accurate than clinical predictions,” that mechanical prediction “substantially outperformed clinical prediction in 33%–47% of studies examined,” and that “in only a few studies (6%–16%)” was the human expert substantially more accurate. Intake-by-gut is a textbook clinical-versus-actuarial problem. A seasoned intake manager’s instinct feels authoritative. Across enough cases, a simple, consistent rubric beats it. No insult to experience: this is one of the most replicated findings in the behavioral sciences.

Fourth, an economic blindness. Every intake call is a free option on a case. Your firm holds the right, but not the obligation, to take the matter, and you are letting options expire without ever recording their strike price. Meanwhile, the litigation-finance industry built rigorous actuarial underwriting of case value in about fifteen years, while the personal injury bar has valued cases by feel for more than a century. One side treats a claim as a quantifiable asset. The other treats it as a hunch.

Fifth, and most concretely, a liability blindness with a dollar figure attached. The clock that most often destroys a case, the statute of limitations, is first set, or first missed, at intake. The ABA Standing Committee on Lawyers’ Professional Liability publishes a quadrennial *Profile of Legal Malpractice Claims*, and across its recent editions administrative errors have accounted for a substantial share of all malpractice claims: 23.15 percent in the 2012–2015 Profile, easing toward about 20 percent in the 2016–2019 edition. These are the failures to calendar, the missed deadlines, the intake that never properly logged the date of loss. Plaintiff’s personal injury is consistently among the highest-frequency practice areas for these claims. The unscored conversation is not only a revenue leak. It is a malpractice vector.

I said I would concede what your CRM already does, and I meant it, so let me draw the line exactly. Your CRM sees the outcome: it converted or it didn’t; it signed or it didn’t; it was calendared or it wasn’t. What no CRM sees, what no dashboard in your building sees, is the conversation that produced the outcome: whether the specialist reflected the caller’s words back or talked over them, whether they asked open questions or fired a checklist, whether they restored a frightened person’s sense of control or stripped it away. The outcome is the shadow. The conversation is the object casting it. You have been studying shadows.

## V. THE INSTRUMENT, AND AN OUTSIDER’S RIGHT TO BUILD IT

A fair question: who are you to build this? I am twenty-three. I am not a lawyer. I ran an intake desk, and then I went looking for everyone who had already solved the problem I had watched us lose cases to. Why should the instrument come from outside the profession rather than inside it?

Theodore Porter answered this before I was born. In *Trust in Numbers* (Princeton University Press, 1995), he showed that rigorous quantification, what he calls “mechanical objectivity,” does not arise where experts are strong and trusted. It arises in the opposite conditions. Quantification becomes “most important where elites are weak, where private negotiation is suspect, and where trust is in short supply.” The scored number is the weapon of the outsider challenging an entrenched profession that has always insisted its judgment can’t be reduced to a metric. Every profession says that, right up until the metric arrives and turns out to be better. The measurement of intake was never going to come from inside a bar that has spent a century assuring itself that good lawyering can’t be counted. It had to come from someone standing outside, holding a stopwatch and a rubric.

But an instrument is only as good as the accountability behind it, and here I want to be more honest than is comfortable. The rubric I use is not magic. Intake QA scores calls against established behavioral frameworks: the reflections and open questions and autonomy-supporting language of motivational interviewing (the MITI/OARS tradition), the empathic-communication moves catalogued in the ECCS coding system, the five elements of psychological first aid described by Stevan Hobfoll, the question-sequencing logic of SPIN, and the peak-end structure of how people remember an experience. These are real, published, validated frameworks. They are also imperfect, and I will tell you exactly where.

The weakest link in this literature is empathy scoring itself. When researchers measure how reliably two trained coders agree on the “empathy” of a recorded session, the overall instrument does well, with intra-class correlations in the good-to-excellent range, but the empathy sub-score specifically can fall apart. In Forsberg and colleagues’ 2007 Swedish validation of the MITI (*Cognitive Behaviour Therapy*, 36:162–169), the empathy sub-score’s reliability dropped as low as 0.42, even as concrete behavioral counts like closed questions held near 0.79. What that tells me is simple, and it governs how I built the product: I do not sell you an empathy meter. No one can reliably score “empathy” as a mystical quantity. What can be scored reliably are the behaviors that produce the feeling of being heard: the count of reflective statements, the ratio of open to closed questions, the presence of autonomy-supporting language, the handling of the emotional peak and the end of the call. I score behavioral proxies, I tell you they are proxies, and I document how they fail where anyone can read it.

That published error rate is not a marketing flourish; it is the answer to a specific economic problem. The economist Alessandro Lizzeri showed in 1999 that a certifier paid by the seller has every incentive to under-disclose: to grade generously, hide its misses, and keep the client happy. Every intake vendor you have ever met is a seller-paid certifier. The only credible way out of that trap is to bind your own hands in public: to state your false-alarm rate where anyone, customer or critic, can hold you to it. That is what the Calibration & Honesty page is. It is me making it expensive to lie.

This is also why I sign my name as analyst of record. The closest analog I know is the professional engineer’s seal. As the National Society of Professional Engineers puts it in its own guidance, “The PE Sign/Stamp is a statement of the PE accepting that accountability,” and the seal means a named human being is “taking personal and professional responsibility for the contents of the work.” An unsigned score is a rumor. A signed score is a stake. When I hand you a Monthly Missed-Revenue Statement, my name is on it the way an engineer’s name is on the beam.

One last thing, and it is not a coincidence I can resist. The discipline that studies exactly this — how people talk, turn by turn, at the edge of their lives — was founded by a thinker trained here in California. Harvey Sacks did his graduate work in sociology at UC Berkeley in the early 1960s, in the intellectual circle around Erving Goffman, before moving south to UCLA and the Los Angeles Suicide Prevention Center, where in 1963 and 1964 he got access to the tape recordings of calls to a suicide hotline and, from those tapes, built what became conversation analysis: the study of how talk actually works, turn by turn. The systematic analysis of recorded distress calls was born in California, from a Berkeley-trained sociologist listening to people at the worst moment of their lives, sixty years ago. I score distress calls in California now. I am not inventing a field. I am finishing a job that started here.

## CODA: THE SPANISH QUALITY PARADOX

I have saved the part I care about most for last, because it is where the accounting and the conscience meet. Spanish-language demand for personal injury representation in California has been recognized, courted, and monetized for more than forty years. Los Defensores, founded in 1984 by Mary Ann Walker (who at twenty-one had become the youngest court interpreter in California history), pioneered joint Spanish-language legal advertising in the year after the ABA’s 1983 Model Rules first cleared the way for brand-name attorney advertising, starting with five Spanish-speaking attorneys and growing into a network of more than 150 law firms. I name it with respect: it proved, decades ago, that the demand is real, enormous, and worth building a business around.

The demand has been measured to the decimal for forty years. The quality of how that demand is handled on the phone has never been measured at all.

Think about what that means alongside Fricker’s testimonial injustice. California is about 40 percent Latino, the state’s largest ethnic group, and the San Joaquin Valley counties at the heart of the state’s agricultural economy run majority Latino (Fresno County alone is 54.5 percent). California has one of the highest shares of limited-English-proficient residents in the nation. And the people generating that Spanish-language demand are, by the numbers, among the most exposed to injury we have. The Bureau of Labor Statistics’ Census of Fatal Occupational Injuries for 2024, released in early 2026, records a fatal-injury rate of 4.3 per 100,000 full-time-equivalent workers for Hispanic or Latino workers, against 3.3 for workers overall, which, as the National Safety Council notes, marks the eighth consecutive year that Hispanic or Latino workers had the highest fatal-injury rate of any group. And in California the exposure is starker still: the BLS reports that Hispanic or Latino workers accounted for 51 percent of all fatal workplace injuries in the state in 2024, against 24 percent nationally.

So the paradox: the community most likely to be hurt, most likely to generate the demand your marketing chases, and most likely to be talking to your firm in a language and a cadence your intake staff may not fully catch, is the community whose intake calls are the most likely to be quietly mishandled and the least likely to be measured. The accented caller suffers the credibility deficit at the exact moment of claiming, no one records it, and the case goes home to lump. Measuring that call is not only good business. It is the first act of respect you can pay a person in the worst week of their life. Hobfoll’s psychological first aid ends on hope: the restoration of a person’s belief that things can be made better. You cannot deliver hope you never bothered to measure. To score the intake conversation is to finally treat the injured caller as what they are (not a conversion event, but a human being mid-way through the bravest and most fragile decision they may ever make) and to hold yourself accountable for how you met them there.

## THE INVITATION

I am not going to end this with a pitch, because a pitch would betray everything I just wrote. I am going to end it with an invitation to be measured.

Free, let Intake QA run a Leak Audit on your firm: send us up to ten of your own recorded intake calls, and I will score them against the rubric I described (behavioral proxies, honestly labeled) and walk you through the signable cases that slipped, live, under strict California all-party-consent discipline. To be explicit: we never advise recording anyone without the consent of all parties. California’s Invasion of Privacy Act (Penal Code §632 and related provisions) treats an unconsented recording of a confidential communication as its own violation, carrying $5,000 in statutory damages per violation, and the plaintiff’s bar (quite possibly your own firm) is aggressively enforcing analogous theories against website tracking. §632 compliance is not a constraint we tolerate. It is a discipline we practice, and it is a feature.

Free is not a discount; it is the same wager as the error rate I have bound myself to publish. I charge nothing until the number survives your scrutiny, and if you continue after that, the fee, when it comes, is flat and never touches your outcomes. The first five firms that continue join the founding beta: they run the desk on their own calls, free while I finish building it, under a mutual nondisclosure agreement, in exchange for structured feedback on what is useful and what is not, and they lock in preferred pricing when it launches. What you receive is a signed accounting of what the conversation, as opposed to the outcome, is costing you. Not the numbers every vendor already quotes you, not the tired secret-shopper statistics about unanswered calls that every intake product on earth waves in your face. Your numbers. About your calls. Signed by a named human being who tells you, in public, what he will and will not claim.

This is what I mean by an independent recovery desk. “Recovery” means analysis: finding the revenue leaking out of a process you never instrumented. It has nothing to do with your fees or your outcomes, and everything to do with the four minutes you have never listened to.

Before you decide, go read the Calibration & Honesty page. Read how the scoring fails, what I will put a number on, and what I refuse to claim until I can prove it. If you find yourself trusting me more after reading what I will not claim, then you already understand the whole argument: in an age when language is free and confidence is manufactured by machines, the only thing worth trusting is speech with something staked behind it.

Let me measure you. Then argue with the number.`;
